### ISSUE TITLE
Internal Server Error when metadata for a large number of pids is requested

### ISSUE THREAD

**Issue by hrmoller** [DBCDK/serviceprovider#369] opened 2016-05-19 11:05 UTC
SP repsonds with statusCode 500 when metadata for a large number of pids are requested at once (apparently 50+).  

__Error message__:
```json
{
  "statusCode": 500,
  "error": "Internal server error"
}
```

Below are two curl's with different sets of pids each containing 30 pids. Both calls resolves just fine but when the two sets of pids are combined into one (third example below) the service responds with the above error message.

__Resolves__:  
```
curl -H "Authorization: Bearer qwerty" -H "Content-Type: application/json" -X GET -d '{ "pids": ["870970-basis:23080044", "870970-basis:28394322", "870970-basis:50674665", "870970-basis:25918673", "870970-basis:51064984", "870970-basis:50911624", "870970-basis:27765033", "870970-basis:51398777", "870970-basis:27556744", "870970-basis:51735919", "870970-basis:51336658", "870970-basis:51469968", "870970-basis:51470168", "870970-basis:29506795", "870970-basis:22121650", "870970-basis:27409636", "870970-basis:22652877", "870970-basis:28465998", "870970-basis:50795993", "870970-basis:28394357", "870970-basis:28771886", "870970-basis:51690575", "870970-basis:51086791", "870970-basis:27477984", "870970-basis:51044959", "870970-basis:51309227", "870970-basis:28394373", "870970-basis:51086872", "870970-basis:28394446", "870970-basis:51054962"], "fields": ["coverUrlFull", "dcTitle", "dcTitleFull", "pid", "workType"], "pretty":true}' "http://platform-i01.dbc.dk:8080/v0/work"
```

```
curl -H "Authorization: Bearer qwerty" -H "Content-Type: application/json" -X GET -d '{ "pids": ["870970-basis:51470117", "870970-basis:50582558", "870970-basis:28394470", "870970-basis:50945561", "870970-basis:27322646", "870970-basis:28769679", "870970-basis:29223793", "870970-basis:27909205", "870970-basis:51630297", "870970-basis:28517181", "870970-basis:28124066", "870970-basis:27108385", "870970-basis:28469500", "870970-basis:29913757", "870970-basis:29822107", "870970-basis:50618404", "870970-basis:28893841", "870970-basis:50739120", "870970-basis:51602102", "870970-basis:51350235", "870970-basis:50930688", "870970-basis:22142429", "870970-basis:25408594", "870970-basis:29822093", "870970-basis:51021827", "870970-basis:51668162", "870970-basis:27607322", "870970-basis:50674622", "870970-basis:28438311", "870970-basis:28769652"], "fields": ["coverUrlFull", "dcTitle", "dcTitleFull", "pid", "workType"], "pretty":true}' "http://platform-i01.dbc.dk:8080/v0/work"
```

__Erroneous__:  
```
curl -H "Authorization: Bearer qwerty" -H "Content-Type: application/json" -X GET -d '{ "pids": ["870970-basis:23080044", "870970-basis:28394322", "870970-basis:50674665", "870970-basis:25918673", "870970-basis:51064984", "870970-basis:50911624", "870970-basis:27765033", "870970-basis:51398777", "870970-basis:27556744", "870970-basis:51735919", "870970-basis:51336658", "870970-basis:51469968", "870970-basis:51470168", "870970-basis:29506795", "870970-basis:22121650", "870970-basis:27409636", "870970-basis:22652877", "870970-basis:28465998", "870970-basis:50795993", "870970-basis:28394357", "870970-basis:28771886", "870970-basis:51690575", "870970-basis:51086791", "870970-basis:27477984", "870970-basis:51044959", "870970-basis:51309227", "870970-basis:28394373", "870970-basis:51086872", "870970-basis:28394446", "870970-basis:51054962", "870970-basis:51470117", "870970-basis:50582558", "870970-basis:28394470", "870970-basis:50945561", "870970-basis:27322646", "870970-basis:28769679", "870970-basis:29223793", "870970-basis:27909205", "870970-basis:51630297", "870970-basis:28517181", "870970-basis:28124066", "870970-basis:27108385", "870970-basis:28469500", "870970-basis:29913757", "870970-basis:29822107", "870970-basis:50618404", "870970-basis:28893841", "870970-basis:50739120", "870970-basis:51602102", "870970-basis:51350235", "870970-basis:50930688", "870970-basis:22142429", "870970-basis:25408594", "870970-basis:29822093", "870970-basis:51021827", "870970-basis:51668162", "870970-basis:27607322", "870970-basis:50674622", "870970-basis:28438311", "870970-basis:28769652"], "fields": ["coverUrlFull", "dcTitle", "dcTitleFull", "pid", "workType"], "pretty":true}' "http://platform-i01.dbc.dk:8080/v0/work"
```

**Comment by damkjaer** [comment] 2016-05-19 17:58
The problem is, that moreinfo (2.1) only takes (about) 49 identifiers at a time.
The suggested fix is, to return empty elements for the moreinfo results in case there are to many identifiers for moreinfo to handle. Alternatively we could propegate the error from moreinfo to the client, but then the work-request would also fail - since API-methods return either an error or some data, but not both.

**Comment by damkjaer** [comment] 2016-05-23 12:44
Rasmus has inserted a check to ensure that at most 20 pids are requested at a time.
Closing this as solved.

**Closed by damkjaer** 2016-05-23 12:44 UTC
